### PR TITLE
Added ability to specify inputCorrectionLevel to generation of QR Codes

### PR DESCRIPTION
**Pull request by kseniya-hydric**

### CODE REVIEW

**Comment by daande** [comment]
@kseniya-hydric I will take a look at getting this merged hopefully later today.

**Comment by kseniya-hydric** [comment]
Any chance you can merge in the next 6 hours? :)

**Comment by yeahdongcn** [comment]
Done

**Comment by kseniya-hydric** [comment]
Ok thank you, I just tried to update my pod and its still pulling in old
version even when I remove a version number. I tried removing the pod and
then installing it back also but still coming through with the old version.

**Comment by yeahdongcn** [comment]
Still pushing... wait a sec.

**Comment by yeahdongcn** [comment]
Please update spec repo first.

**Pull request merged**
