### PR TITLE
Swift 2.3 Compatibility

### PR DESCRIPTION
**Pull request by gblotter**
Updated to be compatible with Swift 2.3

### CODE REVIEW

**Comment by Gerst20051** [comment]
👍

**Comment by gblotter** [comment]
@yeahdongcn Any chance this could be approved and merged?  Thanks!

**Comment by yeahdongcn** [comment]
@gblotter Since the Xcode 8 is still in beta, I will merge your changes once it gets released.

**Comment by yeahdongcn** [comment]
Yeah @gblotter you're right, I merged your changes to a new branch called Swift2.3

**Pull request closed without merging**
