### PR TITLE
Swift 4.0 migration

### PR DESCRIPTION
**Pull request by VFUC**
Swift 4.0 migration, built successfully with the Xcode 9 GM, no merge conflicts

Thanks for this repo and the previous work! Cheers

### CODE REVIEW

**Comment by frranck** [comment]
This is weird, [this datamatrix](https://ibb.co/df6mPQ) doesn't work for me after this PR.

**Comment by Gerst20051** [comment]
Can you resolve merge conflicts? @VFUC

**Comment by VFUC** [comment]
I've resolved the conflicts, the (deprecated) `@objc` Inference is now removed.
I think the CI fails because it uses Xcode 8 rather than 9. I have little experience with Travis, can anyone help out here?

**Comment by VFUC** [comment]
I've updated the sample project as well, it now builds successfully with Swift 4.

⚠️ I ran the sample App and had trouble scanning codes. I'm not sure if this was caused by the Swift 4 migration or if this happened before and should be handled separately.

**Comment by zeusent** [comment]
How is this coming along?

**Comment by frranck** [comment]
@VFUC 
this has changed:
    //open func metadataOutput(captureOutput: AVCaptureMetadataOutput, didOutput metadataObjects: [AVMetadataObject], from connection: AVCaptureConnection) {
  public func metadataOutput(_ output: AVCaptureMetadataOutput, didOutput metadataObjects: [AVMetadataObject], from connection: AVCaptureConnection) {

this is why it doesn't work

**Comment by VFUC** [comment]
Hey, sorry I took a bit to get back to this.
Thanks for the hint, @frranck! You were absolutely right, I fixed the delegate method and the barcode scanning works again in the sample app. The [datamatrix you mentioned](https://ibb.co/df6mPQ) works as well.

I've updated the travis file to use xcode9, hopefully the build will pass this time around. 🙂

**Comment by VFUC** [comment]
Missed the tests oops 😇

**Comment by aleene** [comment]
In UIColorExtension.swift is the line:
`
 let hexString: String = rgba.substring(from: rgba.index(rgba.startIndex, offsetBy: 1))
`

As substring is no longer supported in Swift 4, it should be replaced by:
`
 let index = rgba.index(rgba.startIndex, offsetBy: 1)
`
`
 let hexString = String(rgba[index...])
`

**Comment by aleene** [comment]
You can deprecate `length()` and replace it with `count`.

**Comment by yeahdongcn** [comment]
Thanks.

**Comment by biboran** [comment]
Any chance this pr is going to merged soon?

**Comment by tomaskraina** [comment]
would be awesome to get this merged soon! ✌️

**Comment by neoneye** [comment]
I just tried downloading [this PR](https://github.com/VFUC/RSBarcodes_Swift/tree/swift-4.0) and compiling using Xcode9.2, but I'm seeing these warnings
screen shot 2018-02-02 at 11 04 40

My iPhone6S had no problems scanning the [datamatrix](https://ibb.co/df6mPQ) mentioned earlier in this PR.

**Comment by VFUC** [comment]
Seems like the maintainer has no interest in this PR (which is fine of course, they seem to have looked at Swift 4 compatibility on their own anyways) - If that's not the case, just let me know and I'll have a look at the conflicts and warnings. 🙂

**Pull request merged**
